urls.py
from django.conf.urls import url

from checkcve.views import check_cve
from core.views import probe_index

app_name = 'checkcve'

urlpatterns = [
    url(r'^(?P<pk>\d+)$', probe_index, name='probe_index'),
    url(r'^check/(?P<pk>\d+)$', check_cve, name='check'),
]

templates/checkcve/home.html
<h2>
    {% load static %}
    &nbsp;<img src="{% static 'checkcve/images/checkcve-logo.png' %}" alt="CheckCVE logo" width="110px">
</h2>
<button type="button" class="btn btn-secondary" onclick="window.location.href='/admin/checkcve/checkcve/add/'">Add new
    instance
</button>

<br/><br/>
{% if instances.checkcve %}
<div class="container-fluid">
    <div class="row">
        <div class="center-block">
            <div class="list-group">
                {% load status_cve %}
                {% for instance in instances.checkcve %}
                <a class="list-group-item list-group-item-{{ instance.id|status_cve }} list-group-item-action"
                   href="{% url 'checkcve:probe_index' instance.id %}">{{ instance }} - {{ instance.server.host }}
                </a>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endif %}

templates/checkcve/index.html
{% extends "core/base.html" %}

{% block title %}{{ probe.type }}{% endblock %}

{% block content %}

<h2 style="padding-left:40px;">Instance {{ probe.type }} : {{ probe.name }}</h2>
<div class="row">
    <div class="col-md-6 mb-3" style="padding-left:50px;">
        {% if probe.description != " " %}
        Description:
        <pre>{{ probe.description }}</pre>
        {% endif %}
        Os : {{ probe.server.os }} <br>
        Host : {{ probe.server.host }}<br>
        Created date : {{ probe.created_date }}<br>
        {% if probe.rules_updated_date %}
        Last Check date : {{ probe.rules_updated_date }}
        {% else %}
        Check updated date : Never
        {% endif %}
        <br><br>
        {% load status_cve %}
        <div class="btn-group" role="group">
            <button type="button" class="btn btn-outline-{{ probe.id|status_cve }}"
                    onclick="window.location.href='/{{ probe.type|lower }}/check/{{ probe.id }}'">Check CVE
            </button>
        </div>
        <br>
        {% if messages %}
        <br>
        <ul class="messages">
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissable">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <strong>{{ message|safe }}</strong>
            </div>
            {% endfor %}
        </ul>
        {% endif %}
        <br>
        {% if probe.vulnerabilities %}
        CVE Found :<br>
        {% for cve in probe.vulnerabilities %}
        <div class="btn-group" role="group">
            {% if probe.server.os.name == 'debian' %}
            <button type="button" class="btn btn-outline-danger"
                    onclick="window.open('https://security-tracker.debian.org/tracker/{{ cve }}/')">{{ cve }}
            </button>
            {% else %}
            <button type="button" class="btn btn-outline-danger"
                    onclick="window.open('https://www.cvedetails.com/cve/{{ cve }}/')">{{ cve }}
            </button>
            {% endif %}
        </div>
        {% endfor %}
        {% endif %}
    </div>
</div>
{% endblock %}